version: '3.8'
services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secretAdmin
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: secretUser
    volumes:
      - ./sql:/var/lib/mysql
    ports:
      - "3306:3306"